name: Deploy to EC2

on:
  push:
    branches:
      - main  # Runs when code is pushed to 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu

          # Ensure the project directory exists
          if [ ! -d "labelAutomationDev" ]; then
            git clone git@github.com:ranjithphptech/labelAutomation-ranjithphptech.git labelAutomationDev
          fi

          cd labelAutomationDev

          # Ensure the folder is a git repo and pull latest changes
          if [ ! -d ".git" ]; then
            git init
            git remote add origin git@github.com:ranjithphptech/labelAutomation-ranjithphptech.git
            git fetch origin
            git checkout -b main --track origin/main
          else
            git pull origin main
          fi

          # Check if virtual environment exists, if not create it
          if [ ! -d "env" ]; then
            python3 -m venv env
          fi
          
          # Activate virtual environment and install dependencies
          source env/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          
          # Restart the application
          sudo systemctl restart labelautomation-dev.service
          EOF
