name: Deploy to EC2

on:
  push:
    branches:
      - main  # Runs when code is pushed to 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} | tee -a ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Deploy to EC2
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          set -e  # Stop script execution on error
          
          cd /home/ubuntu

          # Clone repository if it doesn't exist
          if [ ! -d "labelAutomationDev" ]; then
            git clone git@github.com:ranjithphptech/labelAutomation-ranjithphptech.git labelAutomationDev
          fi

          cd labelAutomationDev

          # Ensure it's correctly linked to the remote repository
          if [ ! -d ".git" ]; then
            git init
            git remote add origin git@github.com:ranjithphptech/labelAutomation-ranjithphptech.git
          fi

          # Reset and pull latest changes
          git reset --hard
          git pull origin main

          # Ensure virtual environment exists
          if [ ! -d "env" ]; then
            python3 -m venv env
          fi
          
          # Activate virtual environment and install dependencies
          source env/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          
          # Restart the application
          sudo systemctl daemon-reload
          sudo systemctl restart labelautomation-dev.service
          EOF
